name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 'latest'

    - name: Install CMake
      run: |
        $ErrorActionPreference = 'Stop'
        Invoke-WebRequest -Uri https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1-windows-x86_64.msi -OutFile cmake-installer.msi
        Start-Process msiexec.exe -ArgumentList '/i', 'cmake-installer.msi', '/quiet', '/norestart' -NoNewWindow -Wait
        Remove-Item -Force cmake-installer.msi
        cmake --version

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Build Verification Test
      run: |
        python tests/test_build.py

    - name: Run Client-Server Communication Test
      run: |
        python tests/test_client_server.py
